DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('register/', views.user_register, name="user_register"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_articles, name='all_articles'),
    path('<int:id>/<slug:slug>/', views.article_detail, name="article_detail")
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class PublishArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='publish')


class Article(models.Model):
    STATUS = (
        ('draft', 'پیش نویس'),
        ('publish', 'متتشرشده'),
    )
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, unique=True, allow_unicode=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS, default='draft')
    objects = models.Manager()
    published = PublishArticleManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.id, self.slug])

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField(label="یوزرنیم", max_length=30, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(label="پسورد", max_length=50, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label="یوزرنیم", max_length=30, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email = forms.EmailField(label="ایمیل", widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label="پسورد", max_length=50, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label="تایید پسورد", max_length=50, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     user = User.objects.filter(email=email)
    #     if user.exists():
    #         raise forms.ValidationError("ایمیل تکراری میباشد!")
    #     return email
    #
    # def clean_password2(self):
    #     password1 = self.cleaned_data['password1']
    #     password2 = self.cleaned_data['password2']
    #     if password1 != password2:
    #         raise forms.ValidationError("پسوردها یکسان نمیباشد!")
    #     return password2

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 != p2:
            raise forms.ValidationError("پسوردها یکسان نمیباشد!")
        email = cleaned_data.get('email')
        user = User.objects.filter(email=email)
        if user.exists():
            raise forms.ValidationError("ایمیل تکراری میباشد!")
        user = cleaned_data.get('username')
        user = User.objects.filter(username=user)
        if user.exists():
            raise forms.ValidationError("یوزرنیم تکراری میباشد!")

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserLoginForm,UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'ورود موفقیت آمیز بود!', 'success')
                return redirect('blog:all_articles')
            else:
                messages.warning(request, 'یوزر یا پسسورد اشتباه است!', 'warning')

    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.info(request, 'با موفقیت خارج شدید!', 'info')
    return redirect("accounts:user_login")


def user_register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            User.objects.create_user(username=username, password=password, email=email)
            messages.success(request, 'ثبت نام موفقیت آمیز بود!', 'success')
            return redirect('accounts:user_login')

    else:
        form = UserRegistrationForm()
    return render(request, "accounts/register.html", {"form": form})

blog/views.py
from django.shortcuts import render
from .models import Article
from django.shortcuts import get_object_or_404


def all_articles(request):
    obj = Article.published.all()
    return render(request, 'blog/all_articles.html', context={'obj': obj})


def article_detail(request, id, slug):
    article = get_object_or_404(Article, id=id, slug=slug)
    return render(request, 'blog/article.html', context={'article': article})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="ورود" class="btn btn-primary mb-2">
    </form>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="ثبت نام" class="btn btn-primary mb-2">
    </form>



{% endblock %}

blog/templates/blog/all_articles.html
{% extends 'base.html' %}
{% load static %}
{% block custom_tags %}
    <link rel="stylesheet" href={% static "blog/css/style.css" %}>
{% endblock custom_tags %}
{% block content %}
    <div class="card">
{% for i in obj %}

    <div class="card-body">

        <a href="{{ i.get_absolute_url }}">{{ i.title }}</a>

    </div>


    {% endfor %}
    </div>
{% endblock content %}

blog/templates/blog/article.html
{% extends 'base.html'%}

{% block content %}
<h3>{{ article.title }}</h3>
    <small>{{ article.publish}}</small>
    <hr>
     <p>{{ article.body|safe }}</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>وبلاگ من</title>
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css" integrity="sha384-JvExCACAZcHNJEc7156QaHXTnQL3hQBixvj5RV5buE7vgnNEzzskDtx9NQ4p6BJe" crossorigin="anonymous">
{% load static %}
    <link rel="stylesheet" href={% static "style.css"%}>
    {% block custom_tags %}
    {% endblock custom_tags %}
</head>
<body>
{% include 'inc/navbar.html' %}
<div class="jumbotron">
{% include 'inc/messages.html' %}
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">

    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        </div>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
      <a class="nav-link" href={% url 'blog:all_articles' %}>خانه</a>
        {% if request.user.is_authenticated %}
            <span class="nav-link">خوش آمدید {{ request.user }}</span>


        {% else %}
            <a class="nav-link" href={% url 'accounts:user_login' %}>ورود</a>
            <a class="nav-link" href={% url 'accounts:user_register' %}>ثبت نام</a>


    {% endif %}
  </div>
<div class="navbar-nav ml-auto">
    {% if request.user.is_superuser %}

            <a class="nav-link" href={% url "admin:index" %}>پنل ادمین</a>
    {% endif %}
        {% if request.user.is_authenticated %}
            <a class="nav-link" href={% url 'accounts:user_logout' %}>خروج</a>
{% endif %}
</div>
</nav>